server:
  port: 8000
  servlet:
    context-path: /evdealer

spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  application:
    name: ev-dealer-management
  main:
    allow-bean-definition-overriding: true
  datasource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://${MSSQL_ADDRESS:localhost:14335};databaseName=${MSSQL_DB:evdealer_db};encrypt=true;trustServerCertificate=true
    username: ${MSSQL_SA_USERNAME:sa}
    password: ${MSSQL_SA_PASSWORD:6$3S6zPKpJ+Y2-*J}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.SQLServerDialect

jwt:
  secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
  expiration: ${JWT_EXPIRATION:86400000}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION:604800000}

file:
  directory: ./uploads/thumbnail/image/