server:
  port: 8000
  servlet:
    context-path: /evdealer

spring:
  application:
    name: ev-dealer-management
  main:
    allow-bean-definition-overriding: true
  datasource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://${MSSQL_URI:localhost:14335};databaseName=evdealer_db;encrypt=true;trustServerCertificate=true
    username: sa
    password: 6$3S6zPKpJ+Y2-*J
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: alpha
    display-request-duration: true

logging:
  level:
    org.springframework: TRACE
    org.springframework.security: TRACE

jwt:
  secret: "404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970"
  expiration: 86400000
  refresh-expiration: 604800000