server:
  port: 8000
  servlet:
    context-path: /evdealer

spring:
  application:
    name: ev-dealer-management
  datasource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://${MSSQL_DB_HOST:localhost}:${MSSQL_DB_PORT:1433};databaseName=evdealer_db;encrypt=true;trustServerCertificate=true
    username: sa
    password: 12345
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect

